version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis1_django_network
    volumes:
      - gis1_static:/data/static/
      - gis1_media:/data/media/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: gis1_django:4
    networks:
      - gis1_django_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - gis1_static:/home/gis_web_01/staticfiles/
      - gis1_media:/home/gis_web_01/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis1_django_network
    volumes:
      - gis1_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234
      MARIADB_ROOT_PASSWORD: password1234@!

networks:
  gis1_django_network:

volumes:
  gis1_static:
  gis1_media:
  gis1_mariadb:

secrets:
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  DJANGO_SECRET_KEY:
    external: true